### ISSUE TITLE
how to set GET,POST and so on to a handle

### ISSUE THREAD

**Issue by ufwfqpdgv** [kujtimiihoxha/kit#13]
just like title,how to...

func makeCreateHandler(m *http.ServeMux, endpoints endpoint.Endpoints, options []http1.ServerOption) {
	m.Handle("/create", http1.NewServer(endpoints.CreateEndpoint, decodeCreateRequest, encodeCreateResponse, options...))
}

**Comment by kujtimiihoxha** [comment]
@ufwfqpdgv by default `kit` uses the golang `http` package and handling request methods would be up to you, but when generating the service you could use use `--gorilla` flag to use the gorilla mux router this would then generate something like:

```
func makeCreateHandler(m *mux.Router, endpoints endpoint.Endpoints, options []http.ServerOption) {
   m.Methods("POST").Path("/create").Handler(
      handlers.CORS(
         handlers.AllowedMethods([]string{"POST"}),
         handlers.AllowedOrigins([]string{"*"}),
      )(http.NewServer(endpoints.CreateEndpoint, decodeGetRequest, encodeGetResponse, options...)))
}
```
You can read https://medium.com/@kujtimii.h/creating-a-todo-app-using-gokit-cli-20f066a58e1 about how to use kit.
