### ISSUE TITLE
How to add self-created middleware to the addDefaultEndpointMiddleware automaticly

### ISSUE THREAD

**Issue by GrantZheng** [kujtimiihoxha/kit#18]
Hi， like the title, how to add self-created middleware to the addDefaultEndpointMiddleware function automaticly,l like the InstrumentingMiddleware and the LoggingMiddleware?
thanks

**Comment by kujtimiihoxha** [comment]
The only way you can add self created middleware at the moment is to use the `getServiceMiddleware` function in `cmd/service/service.go` 
```go
func getServiceMiddleware(logger log.Logger) (mw []service.Middleware) {
	mw = []service.Middleware{}
	mw = addDefaultServiceMiddleware(logger, mw)
	// Append your middleware here
	return
}
```
