### ISSUE TITLE
thrift.TClient undefined

### ISSUE THREAD

**Issue by metacatdud** [kujtimiihoxha/kit#3]
I'm trying out this CLI tool as it looks the most capable from what I see so far but i have this issue with thrift.TClient
```
# user/vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:210:5: undefined: thrift.TClient
```
It this point the only thing i did is to follow your tutorial. Can you please help me with this?
Thanks you.

**Comment by kujtimiihoxha** [comment]
This is actually an issue with the vendor, not with the generator, probably some version mismatch between gokit and zipkin-go-opentracing try specifying an older version of that dependancy on your glide file.

**Comment by metacatdud** [comment]
Hmm. Ok. I'll try that.
 Thank you very much!

**Comment by liukgg** [comment]
@metacatdud  Have you solved this problem?

**Comment by metacatdud** [comment]
Yes, It was indeed a version mismatch

**Comment by liukgg** [comment]
How did you solve it? Could you please provide some information? Thanks!

**Comment by maqingxiang** [comment]
How did you solve it? Could you please provide some information? Thanks too!

**Comment by liukgg** [comment]
I solved this problem by: 
```bash
$ rm Gopkg.lock
$ dep ensure
```
