### ISSUE TITLE
Please update it to work with Go modules, instead of GOPATH

### ISSUE THREAD

**Issue by cyantarek** [kujtimiihoxha/kit#52]

**Comment by jllanes-ss** [comment]
Hi @cyantarek 

¿How do you fix this issue?

Regards

**Comment by GrantZheng** [comment]
> Hi @cyantarek
> 
> ¿How do you fix this issue?
> 
> Regards

Hi， you could try to use it that supports the mod feature（https://github.com/GrantZheng/kit）
