### ISSUE TITLE
When I use kit tool to create http client library, I do not clearly know how to set http request timeout

### ISSUE THREAD

**Issue by GrantZheng** [kujtimiihoxha/kit#8]
Hi:
When I use kit tool to create http client library, I do not clearly know how to set http request timeout?
Could you help me, thanks!

**Comment by kujtimiihoxha** [comment]
@GrantZheng have you figured out how to do this?

**Comment by GrantZheng** [comment]
> @GrantZheng have you figured out how to do this?

Yes, I use the http.SetClient function in "github.com/go-kit/kit/transport/http", such as:

```
func DefaultHttpOptions() map[string][]http.ClientOption {	
   options := map[string][]http.ClientOption{
		"Build":            {http.SetClient(&http1.Client{Timeout: 100 * time.Millisecond})}
}
```

**Comment by kujtimiihoxha** [comment]
Great 👍
